import { toast } from 'react-toastify';

export default function RecommendationCard({ riskScore = 0, result }) {
    const isHighRisk = riskScore >= 60;

    const exportReport = () => {
        if (!result) {
            toast.error('No analysis data to export');
            return;
        }

        const timestamp = new Date().toISOString();
        const analyzedAt = result.analyzedAt ? new Date(result.analyzedAt).toLocaleString() : 'N/A';

        const report = `
════════════════════════════════════════════════════════════════
                    DDoS Watch — IP Threat Intelligence Report
════════════════════════════════════════════════════════════════

Generated: ${new Date().toLocaleString()}
Analyzed:  ${analyzedAt}

────────────────────────────────────────────────────────────────
 TARGET IP
────────────────────────────────────────────────────────────────
IP Address:       ${result.ipAddress || 'N/A'}
IP Version:       IPv${result.ipVersion || 4}

────────────────────────────────────────────────────────────────
 DATA SOURCE: AbuseIPDB
────────────────────────────────────────────────────────────────
Abuse Score:      ${result.abuseScore ?? 'N/A'} / 100
Total Reports:    ${result.totalReports ?? 'N/A'}
Distinct Users:   ${result.numDistinctUsers ?? 'N/A'}
ISP:              ${result.isp || 'N/A'}
Usage Type:       ${result.usageType || 'N/A'}
Domain:           ${result.domain || 'N/A'}
Hostnames:        ${result.hostnames?.length ? result.hostnames.join(', ') : 'None'}
Is Tor Node:      ${result.isTor === true ? 'Yes' : result.isTor === false ? 'No' : 'N/A'}
Is Whitelisted:   ${result.isWhitelisted === true ? 'Yes' : result.isWhitelisted === false ? 'No' : 'N/A'}
Last Reported:    ${result.lastReportedAt ? new Date(result.lastReportedAt).toLocaleString() : 'Never'}

────────────────────────────────────────────────────────────────
 DATA SOURCE: ipwho.is (Geolocation)
────────────────────────────────────────────────────────────────
Country:          ${result.country || 'N/A'} (${result.countryCode || ''})
Region:           ${result.regionName || 'N/A'} (${result.region || ''})
City:             ${result.city || 'N/A'}
District:         ${result.district || 'N/A'}
ZIP:              ${result.zip || 'N/A'}
Latitude:         ${result.lat ?? 'N/A'}
Longitude:        ${result.lon ?? 'N/A'}
Timezone:         ${result.timezone || 'N/A'}
Organization:     ${result.org || 'N/A'}
AS Number:        ${result.as || 'N/A'}
Proxy Detected:   ${result.isProxy === true ? 'Yes' : result.isProxy === false ? 'No' : 'N/A'}

────────────────────────────────────────────────────────────────
 RISK ASSESSMENT
────────────────────────────────────────────────────────────────
Risk Score:       ${riskScore} / 100
Threat Level:     ${riskScore >= 80 ? 'CRITICAL' : riskScore >= 60 ? 'HIGH' : riskScore >= 40 ? 'MODERATE' : riskScore >= 20 ? 'LOW' : 'MINIMAL'}
Recommendation:   ${isHighRisk ? 'BLOCK TRAFFIC — Immediate blocking is recommended' : 'MONITOR — Continued monitoring is advised'}

════════════════════════════════════════════════════════════════
 Report generated by DDoS Watch • https://github.com/real-name-not-found
════════════════════════════════════════════════════════════════
`.trim();

        // Download as .txt file
        const blob = new Blob([report], { type: 'text/plain;charset=utf-8' });
        const url = URL.createObjectURL(blob);
        const a = document.createElement('a');
        a.href = url;
        a.download = `ddos-ip-report_${result.ipAddress}_${timestamp.split('T')[0]}.txt`;
        document.body.appendChild(a);
        a.click();
        document.body.removeChild(a);
        URL.revokeObjectURL(url);

        toast.success('Report exported successfully');
    };

    return (
        <div className="border-r border-b border-black flex flex-col">
            <div className="flex-1 bg-black text-white p-8 flex flex-col justify-between min-h-[320px]">
                <span className="text-[10px] uppercase tracking-widest opacity-60">Recommendation</span>
                <div>
                    <h3 className="font-serif text-2xl mb-2">
                        {isHighRisk ? 'Block Traffic' : 'Monitor'}
                    </h3>
                    <p className="text-neutral-400 text-sm font-light leading-relaxed">
                        {isHighRisk
                            ? 'Due to high confidence and critical risk score, immediate blocking is recommended.'
                            : 'Moderate risk detected. Continued monitoring is advised.'}
                    </p>
                </div>
                <button
                    onClick={exportReport}
                    className="bg-white text-black w-full py-3 text-[10px] uppercase tracking-widest hover:bg-neutral-200 transition-colors mt-4 flex items-center justify-center gap-2"
                >
                    <span className="material-symbols-outlined text-sm">download</span>
                    Export Report
                </button>
            </div>
        </div>
    );
}
