import { toast } from 'react-toastify';
import { getAbuseStatus } from '../utils/helpers';

export default function RecommendationCardIntegrated({ riskScore = 0, result }) {
    const isWhitelisted = result?.isWhitelisted === true;
    const { level: finalLabel } = getAbuseStatus(riskScore, isWhitelisted);
    const recommendation = isWhitelisted
        ? 'AbuseIPDB marks this IP as whitelisted. You can treat the AI prediction as advisory and avoid acting on the model output alone.'
        : finalLabel === 'CRITICAL'
            ? 'AbuseIPDB indicates severe abuse activity. Investigate immediately before allowing traffic.'
            : finalLabel === 'HIGH'
                ? 'AbuseIPDB indicates elevated abuse activity. Review the provider evidence before blocking or rate limiting.'
                : finalLabel === 'MODERATE'
                    ? 'AbuseIPDB shows moderate abuse activity. Keep monitoring and review additional context before taking action.'
                    : 'AbuseIPDB does not currently indicate severe abuse. Continue monitoring this IP normally.';
    const actionTitle = finalLabel === 'HIGH' || finalLabel === 'CRITICAL'
        ? 'Block Traffic'
        : finalLabel === 'MODERATE'
            ? 'Keep Monitoring'
            : finalLabel === 'WHITELISTED'
                ? 'Whitelisted'
                : 'Low Immediate Risk';

    const exportReport = () => {
        if (!result) {
            toast.error('No analysis data to export');
            return;
        }

        // The exported report combines legacy provider data with the new ML section
        // so the user gets one complete analyst-facing summary.
        const timestamp = new Date().toISOString();
        const analyzedAt = result.analyzedAt ? new Date(result.analyzedAt).toLocaleString() : 'N/A';
        const mlProbability = typeof result.mlMaliciousProbability === 'number'
            ? `${(result.mlMaliciousProbability * 100).toFixed(2)}%`
            : 'N/A';

        const report = `
================================================================
                    DDoS Watch - IP Threat Intelligence Report
================================================================

Generated: ${new Date().toLocaleString()}
Analyzed:  ${analyzedAt}

----------------------------------------------------------------
 TARGET IP
----------------------------------------------------------------
IP Address:       ${result.ipAddress || 'N/A'}
IP Version:       IPv${result.ipVersion || 4}

----------------------------------------------------------------
 DATA SOURCE: AbuseIPDB
----------------------------------------------------------------
Abuse Score:      ${result.abuseScore ?? 'N/A'} / 100
Total Reports:    ${result.totalReports ?? 'N/A'}
Distinct Users:   ${result.numDistinctUsers ?? 'N/A'}
ISP:              ${result.isp || 'N/A'}
Usage Type:       ${result.usageType || 'N/A'}
Domain:           ${result.domain || 'N/A'}
Hostnames:        ${result.hostnames?.length ? result.hostnames.join(', ') : 'None'}
Is Tor Node:      ${result.isTor === true ? 'Yes' : result.isTor === false ? 'No' : 'N/A'}
Is Whitelisted:   ${result.isWhitelisted === true ? 'Yes' : result.isWhitelisted === false ? 'No' : 'N/A'}
Last Reported:    ${result.lastReportedAt ? new Date(result.lastReportedAt).toLocaleString() : 'Never'}

----------------------------------------------------------------
 DATA SOURCE: ipwho.is (Geolocation)
----------------------------------------------------------------
Country:          ${result.country || 'N/A'} (${result.countryCode || ''})
Region:           ${result.regionName || 'N/A'} (${result.region || ''})
City:             ${result.city || 'N/A'}
District:         ${result.district || 'N/A'}
ZIP:              ${result.zip || 'N/A'}
Latitude:         ${result.lat ?? 'N/A'}
Longitude:        ${result.lon ?? 'N/A'}
Timezone:         ${result.timezone || 'N/A'}
Organization:     ${result.org || 'N/A'}
AS Number:        ${result.as || 'N/A'}
Proxy Detected:   ${result.isProxy === true ? 'Yes' : result.isProxy === false ? 'No' : 'N/A'}

----------------------------------------------------------------
 ML ASSESSMENT
----------------------------------------------------------------
ML Probability:   ${mlProbability}
ML Band:          ${result.mlRiskBand || 'N/A'}
Low Threshold:    ${result.mlLowRiskThreshold ?? 'N/A'}
High Threshold:   ${result.mlHighRiskThreshold ?? 'N/A'}

----------------------------------------------------------------
 FINAL RISK ASSESSMENT
----------------------------------------------------------------
Risk Score:       ${riskScore} / 100
Threat Level:     ${finalLabel}
Recommendation:   ${recommendation}

================================================================
 Report generated by DDoS Watch - https://github.com/real-name-not-found
================================================================
`.trim();

        const blob = new Blob([report], { type: 'text/plain;charset=utf-8' });
        const url = URL.createObjectURL(blob);
        const a = document.createElement('a');
        a.href = url;
        a.download = `ddos-ip-report_${result.ipAddress}_${timestamp.split('T')[0]}.txt`;
        document.body.appendChild(a);
        a.click();
        document.body.removeChild(a);
        URL.revokeObjectURL(url);

        toast.success('Report exported successfully');
    };

    return (
        <div className="border-r border-b border-black flex flex-col">
            <div className="flex-1 bg-black text-white p-8 flex flex-col justify-between min-h-[320px]">
                <span className="text-[10px] uppercase tracking-widest opacity-60">Recommendation</span>
                <div>
                    <h3 className="font-serif text-2xl mb-2">
                        {actionTitle}
                    </h3>
                    <p className="text-neutral-400 text-sm font-light leading-relaxed">
                        {recommendation}
                    </p>
                </div>
                <button
                    onClick={exportReport}
                    className="bg-white text-black w-full py-3 text-[10px] uppercase tracking-widest hover:bg-neutral-200 transition-colors mt-4 flex items-center justify-center gap-2"
                >
                    <span className="material-symbols-outlined text-sm">download</span>
                    Export Report
                </button>
            </div>
        </div>
    );
}
